
spring:
  application:
    name: deepexi-spring-cloud
  profiles:
    active: local
  aop:
    proxy-target-class: true
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  datasource:
#      username: 'root'
#      password: 'root'
#      url: "jdbc:mysql://127.0.0.1:3306/data?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8"
#      driver-class-name: com.mysql.jdbc.Driver
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/data?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.deepexi.domain.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']
swagger:
  base-package: com.deepexi.controller
  info:
    title: deepexi-spring-cloud
server:
  error:
    include-stacktrace: always
    include-exception: true
  port: 8081
logging:
  file: 'logs/${spring.application.name}.log'

#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://user:pass@127.0.0.1:8761/eureka/'
feign:
  hystrix:
    enabled: true
#shiro:
#  web:
#    mode: stateless
#    filter-chain-definition:
#      authc:
#        - /v1/**
#      anon:
#        - /**
febs:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/favicon.ico
    # token有效期，单位秒
    jwtTimeOut: 3600
